baseURL: 'https://lewisharvey96.github.io/'
title: 'About me'
theme: 'PaperMod'

ShowToc: true

imaging:
  quality: 100
  resampleFilter: Lanczos

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Posts
          url: posts/
          weight: 10
        - name: Search
          url: search/
          weight: 10
  
params:
  social: true
  profileMode:
    enabled: true
    title: "Lewis Harvey" # optional default will be site title
    subtitle: "Data Scientist with a passion for the energy sector."
    imageUrl: "headshot.jpg" # optional
#    imageWidth: 200 # custom size
#    imageHeight: 200 # custom size
    buttons:
    - name: Posts
      url: "/posts"

  socialIcons: # optional
    - name: linkedin
      title: Go to LinkedIn
      url: "https://www.linkedin.com/in/lewis-harvey-786b8b177/"
    - name: github
      title: Go to Github
      url: "https://github.com/lewisharvey96"

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: True

contentTypes:
  text/asciidoc: {}
  text/org: {}
  text/pandoc: {}
  text/rst: {}

security:
  enableInlineShortcodes: true